### ISSUE TITLE
Integration of data from CCI lakes

### ISSUE THREAD

**Issue by santilland** [eurodatacube/eodash#2202]
Source:
https://climate.esa.int/en/projects/lakes/data/
CCI has shapefile for global lakes, and csv with names.
NetCDF data -  example notebook to retrieve data
Need for conversion to COG?

Parameters of interest:

- Surface water temperature
- Water level/height
- Water level extent

Maybe of interest:
https://collections.eurodatacube.com/clms-lake-water-quality/

**Comment by santilland** [comment]
Sara to provide list of lakes (name and country)

**Comment by santilland** [comment]
For EOX -  extract "subaoi" from lakes shapefile and create indicator.
For some lakes s2 and other sources might be used, whatever source we use we would need a list of dates where source is available over the lake extent

**Comment by aapopescu** [comment]
@gunbra32, we'd like to use the the following CLMS dataset in RACE and we'd need your support to access this via EDC. 
https://collections.eurodatacube.com/clms-lake-water-quality/ 

Cc: @AlessandroScremin

**Comment by santilland** [comment]
Hello @j08lue,
we are working on the integration of data for the trilateral eodashboard preparing for a lake story that is expected also to be used as possible example for foss4g workshop.
In order to have data also from NASA could you help us locate data from either Landsat, HLS, PlanetScope that covers the lakes listed further up?

**Comment by j08lue** [comment]
> could you help us locate data from either Landsat, HLS, PlanetScope that covers the lakes listed further up?

I will look into that, asking whether there is a preference on the NASA side for which data to provide.

## Questions:
1. Do we have AOIs for these lakes somewhere already?
2. What time range and temporal resolution would be preferred?
3. Any other criteria for the scenes to present - low cloud cover or something?

**Comment by AlessandroScremin** [comment]
@j08lue 
here are the AOIs centroids points..

Tonle Sap (Boeng Tonle Chhma - 12.793990, 104.154704  (Cambodia)
Vanern - 58.868459, 13.344541 (Sweden)
Balaton - 46.838203, 17.712136 (Hungary)
Biwa - 35.301566, 136.133431     (Japan)

**Comment by j08lue** [comment]
Btw, is the story already written up somewhere or can you briefly outline the angle it will have?

That would help me understand what kind of data would be relevant to feature, so we deliver something that adds maximum value to your story.

Like, what would you want to show with Landsat or HLS surface reflectance? The general landscape around the lakes? Or an evolution of features seen on the lake (ice, algal blooms or so) over specific periods?

For example, here is a nice cloud-free Landsat-9 scene of the Vännern lake on 8th of May 2023:

![image](https://github.com/eurodatacube/eodash/assets/3404817/7037172e-0c8d-4c4e-a359-4f1377df7a46)

(Picked using [Microsoft Planetary Computer](https://planetarycomputer.microsoft.com/explore?c=13.3170%2C58.5118&z=6.75&v=2&d=landsat-c2-l2&s=false%3A%3A100%3A%3Atrue&ae=0&sr=desc&m=Most+recent+%28low+cloud%29&r=Natural+color))

I see you do not have Planetary Computer configured as a source in the EO Dashboard, @santilland. Would that also be an option for you to get dynamic tiles for example for Landsat data? The tiler URL for the scene shown above would be

https://planetarycomputer.microsoft.com/api/data/v1/item/tiles/WebMercatorQuad/{z}/{x}/{y}@2x?collection=landsat-c2-l2&item=LC09_L2SP_195019_20230508_02_T1&assets=red&assets=green&assets=blue&color_formula=gamma+RGB+2.7%2C+saturation+1.5%2C+sigmoidal+RGB+15+0.55&nodata=0&format=png

**Comment by AlessandroScremin** [comment]
@j08lue 
nice to see it with landsat. What we are going to provide are 3 indicaotrs related to the lake:
water surface temperature timeseries and maps
water lake extent timeseries
water level timeseries

I don't think with landsat you are able to retrieve all those information. Maybe surface temperature. Lake extent I see too diffult with the spatial resolution of Landsat.

At leat this was the idea to be onfrmed by @aapopescu

**Comment by aapopescu** [comment]
> @gunbra32, we'd like to use the the following CLMS dataset in RACE and we'd need your support to access this via EDC. https://collections.eurodatacube.com/clms-lake-water-quality/
> 
> Cc: @AlessandroScremin

Follow-up on this, maybe @AliceBalfanz can help. Thanks!

**Comment by pont-us** [comment]
The LWQ 300m dataset is currently available in an S3 bucket, but only for the time range 2018-01-1 to 2020-12-21:

```python
from xcube.core.store import new_data_store
data_store = new_data_store('s3', root='cop-services')
lwq = data_store.open_data('LWQ-NRT-300m.zarr')
```

**Comment by aapopescu** [comment]
> I will try to find the story text - it is probably already written up - so I understand what kind of data would add most value to your story.

Hi, @j08lue , the story is drafted at this link and you should have access https://docs.google.com/document/d/1Nc0bZhd6Myz6kTZvXPSgkJamYN4iHjm7D-lpCOtCx8k/edit 


> 
> In particular, what would you want to show with Landsat or HLS surface reflectance? The general landscape around the lakes? Or an evolution of features seen on the lake (ice, algal blooms or so) over specific periods?

We are looking to show the variation in the water level and water quality, so what we need to visualise is:
- the lake itself and the landscape around it, with the longest time coverage available
- chlorophyll concentration, temperature


> 
> For example, here is a nice cloud-free Landsat-9 scene of the Vännern lake on 8th of May 2023:
> 
> ![image](https://user-images.githubusercontent.com/3404817/240878578-7037172e-0c8d-4c4e-a359-4f1377df7a46.png)
> 
> (And a [Microsoft Planetary Computer](https://planetarycomputer.microsoft.com/explore?c=13.3170%2C58.5118&z=6.75&v=2&d=landsat-c2-l2&s=false%3A%3A100%3A%3Atrue&ae=0&sr=desc&m=Most+recent+%28low+cloud%29&r=Natural+color) tiler URL: `https://planetarycomputer.microsoft.com/api/data/v1/item/tiles/WebMercatorQuad/{z}/{x}/{y}@2x?collection=landsat-c2-l2&item=LC09_L2SP_195019_20230508_02_T1&assets=red&assets=green&assets=blue&color_formula=gamma+RGB+2.7%2C+saturation+1.5%2C+sigmoidal+RGB+15+0.55&nodata=0&format=png`)
> 
> If you would prefer to get PlanetScope scenes, we can probably also get those. In the COVID Dashboard API, we had a proxy for selected [PSScene](https://developers.planet.com/docs/data/psscene/)s. That is not part of the VEDA API, but maybe we can find a different mechanism to provide them, if needed.

Higher resolution imagery is not essential but could be useful. Would it be feasible within the next 2 weeks?

**Comment by santilland** [comment]
@leahsturm to provide list of s2 acquisition dates --> EOX to add s2 indicator with dates for lakes with provided dates

**Comment by santilland** [comment]
Data to be explored per lake:
Aral sea - extension (S1 or S2)
Lake Biwa - extension (S1 or S2) , temperature (S3 if res. enough) and quality (S2)
Colorado River (and Lake Powel) - extension
Tonlé Sap - level
Lake Varnen - water quality (S2 or S3 if resolution is enough)
Lake Balaton - ice cover comparison between different winters (S1)

**Comment by gmilcinski** [comment]
@Dorothyrono - can someone in your team take care for ingestion of this collection in the Sentinel Hub? And/or provide to Alessandro the script so that he can do this himself?

**Comment by aapopescu** [comment]
> @AlessandroScremin @aapopescu @gmilcinski If Sentinel Hub is used, we are obviously out here. Our approach would have been to serve the cube (or just the AOIs) through xcube server (the cube is actually already in the viewer but we would have to optimise it for performance).

@santilland , @gunbra32 let's do this exercise. I'd like to demonstrate visualising on RACE data served by the xcube viewer.

**Comment by Dorothyrono** [comment]
> > @AlessandroScremin @aapopescu @gmilcinski If Sentinel Hub is used, we are obviously out here. Our approach would have been to serve the cube (or just the AOIs) through xcube server (the cube is actually already in the viewer but we would have to optimise it for performance).
> 
> @santilland , @gunbra32 let's do this exercise. I'd like to demonstrate visualising on RACE data served by the xcube viewer. Concurrently, let's bring this data in SH. Would be great if @AlessandroScremin could have access to the required script. Thanks, @Dorothyrono

@AlessandroScremin 
The data is ingested in your SH account    

collection: `Lake Water Quality` id: `ef59d045-a0cd-4ce0-a25d-5da91e70e965` 

(Please ignore the ingestion errors that appears in the collection- it does not affect the collection in any way.)

**Comment by aapopescu** [comment]
> > @leahsturm to provide list of s2 acquisition dates (taken from https://apps.sentinel-hub.com/eo-browser/) looking for good visibility (as little cloud cover as possible) and where changes in lake extent can be seen --> EOX to add s2 indicator with dates for lakes with provided dates
> 
> Here is the list with the Sentinel2 acquisition dates. I noted down the most possible number of cloud free images for each lake to ensure an extensive documentation of the change processes. [Sentinel2_lakes.xlsx](https://github.com/eurodatacube/eodash/files/11707292/Sentinel2_lakes.xlsx)

Thanks, @leahsturm, this is great! @lubojr (Cc: @santilland ) we should integrate these S-2 images over the lakes in the list. Thanks!

**Comment by santilland** [comment]
Thanks, @leahsturm created new issue #2251 to keep track of integration of this separately

**Comment by santilland** [comment]
> Good! This would also be a great use case or the xcube viewer + server activity.

> As written above, we will let you know once we optimised the cube.
The server provides the following APIs: https://edc-api.brockmann-consult.de/api/openapi.html
I assume th WMTS will be used here?

@gunbra32 i was not aware of a viewing endpoint for xcube data, with WMTS we should be able to directly integrate it then, not sure about what authentication would be needed for the endpoint though.

The link you provide seems to be configured for a localhost server, so it is not possible to try out things, not sure if this is intended.

In any case let us know once you have optimized the data and which WMTS endpoint we can use to visualize it, thanks!

**Comment by santilland** [comment]
> @AlessandroScremin
The data is ingested in your SH account

> collection: Lake Water Quality id: ef59d045-a0cd-4ce0-a25d-5da91e70e965

great! thank you @Dorothyrono .
@AlessandroScremin could you create a visualization layer based on the data in SH and give us the layer identifier?

**Comment by AlessandroScremin** [comment]
> @AlessandroScremin The data is ingested in your SH account
> 
> collection: `Lake Water Quality` id: `ef59d045-a0cd-4ce0-a25d-5da91e70e965`
> 
> (Please ignore the ingestion errors that appears in the collection- it does not affect the collection in any way.)

Dear @Dorothyrono thanks a lot for the support

I was looking at the visualisation layer as well and at the two layers:
Turbidity mean
Water qualitu true color.

what is not much clear to me in the true color is if it is binary mask ot what else?
this is the result from the layer for true color:
this image over north italy central europe

![image](https://github.com/eurodatacube/eodash/assets/65602207/d8ca3ee9-a4d7-455b-9013-58862d7835ac)

**Comment by AlessandroScremin** [comment]
> great! thank you @Dorothyrono . @AlessandroScremin could you create a visualization layer based on the data in SH and give us the layer identifier?

@santilland 
these are the layers as provided
if any updates will come I will update those layers evelscripts


Lake_Wate_Quality_TrueColor | ID: LAKE_WATE_QUALITY_TRUECOLOR 

Lake_water_quality_Turbidity_mean | ID: LAKE_WATER_QUALITY_TURBIDITY_MEAN |

**Comment by AlessandroScremin** [comment]
@santilland @lubojr @aapopescu 

Dears I created the table in the GEODB with timeseries (2010-2020) for:
Vanern: water lake extent
Vanern: water lake level

the two tables are here:
database="eodash"
table_name = "Lake_water_extent_tri_timeseries"

database="eodash"
table_name = "Lake_water_level_tri_timeseries"

as discussed there isn't a match with any maps, these are only timeseries to be extracted with the chart.

let me know if else is needed or to be clarified.
Anyway I'm still working for the water surface temperatures (timeseries)

Alessandro

**Comment by AlessandroScremin** [comment]
@aapopescu @santilland @dmoglioni 

Unfortunately I won't be able to join the weekly meeting tomorrow so I will try to summaryze here the tasks done on our side:
DONE
- JN for filtering the S2L2A images providing a list of dates with full coverage of AOI and Cloud free
- ESA CCI lake Water extent timeseries for Vanern (Sweden, timerange 2010-2020) ingested in the GEODB (database="eodash"
table_name = "Lake_water_extent_tri_timeseries")
- ESA CCI Lake Water Level timeseries for Vanern (Sweden, timerange 2010-2020) ingested in the GeoDB (database="eodash"
table_name = "Lake_water_level_tri_timeseries"
-LWQ 300m (from xcube) ingested in Sentinel Hub. Visaulisation layer provided in EDC: 
 - Lake_Wate_Quality_TrueColor | ID: LAKE_WATE_QUALITY_TRUECOLOR (some issue in visualisation of non lake pixels)
 - Lake_water_quality_Turbidity_mean | ID: LAKE_WATER_QUALITY_TURBIDITY_MEAN ((some issue in visualisation of non lake pixels)
 - Maps of water surface temperature for:
  - Vanern, Tonle, Biwa and Balaton (visualisation layer--> "lake_water_temperature" | ID: LAKE_WATER_TEMPERATURE)

TO DO
- generation and ingestion of water surface temperature timeseries into GeoDB for the 4 lakes

**Comment by lubojr** [comment]
@AlessandroScremin Which is the collection id for the layer LAKES_SURFACE_WATER_TEMPERATURE (so we can extract the list of dates automatically)

**Comment by lubojr** [comment]
@Dorothyrono We tried to extract the list of dates for the client for the given collection using the usual WFS call that we use for other indicators in eodash:
https://services.sentinel-hub.com/ogc/wfs/<sh-id>?REQUEST=GetFeature&srsName=EPSG:4326&TIME=1900-01-01/3000-02-01&outputformat=application/json&TYPENAMES=DSS10-ef59d045-a0cd-4ce0-a25d-5da91e70e965&BBOX=-180,90,180,-90
but it is returning an empty array of features:
```{
    "type": "FeatureCollection",
    "features": [
            ]
}```
Has the functionality been somehow moved or not made available for this one? Is there any other way how we could extract the list of individual dates for configuring our WMS TIME array?

**Comment by AlessandroScremin** [comment]
> @AlessandroScremin Which is the collection id for the layer LAKES_SURFACE_WATER_TEMPERATURE (so we can extract the list of dates automatically)

@lubojr 

the id is: 97cd622e-40bf-44d6-838b-7ea57a4cc3f5

**Comment by lubojr** [comment]
@AlessandroScremin @santilland @leahsturm
fyi @aapopescu 
There has been some progress on integrating the available data to the eodashboard. https://eodash-trilateral-testing.eox.at/cci-lakes-integration/

All new indicators were added as 'oceans' theme for now.
## New POIs:

### Sentinel 2 L2A over 5 lakes with preselected dates by @leahsturm

Looks great! Still missing some markdown story but that is it I think?

### Surface Temperature Maps

> * Maps of water surface temperature for:
>   
>   * Vanern, Tonle, Biwa and Balaton (visualisation layer-->  Lakes_surface_water_temperature | ID: LAKES_SURFACE_WATER_TEMPERATURE

- [ ] In the provided collection, there are no scenes over Tonle (bbox query via wfs does not find anything over the tonle bbox or nearby), just the 3 other lakes. Error in ingestion or intention?
- I have checked several times for individual lakes and the coverage is sometimes very very spotty, but that is a data problem.
- [ ] Which legend should I reference ? (Which evalscript was used and what are the units)?
- [ ] Story missing

### Lake Water Quality
> collection: `Lake Water Quality` id: `ef59d045-a0cd-4ce0-a25d-5da91e70e965`

- [ ] WFS query on this collection does not find any scenes. @AlessandroScremin is this the newest collection for the layers  LAKE_WATE_QUALITY_TRUECOLOR and LAKE_WATER_QUALITY_TURBIDITY_MEAN ?
- [ ] Nothing integrated yet as we need a list of dates

**Comment by AlessandroScremin** [comment]
@lubojr 

Lakes surface temperature dates in the list attached. (added also Tonle even if not yet ingested)

[Balaton_dates.txt](https://github.com/eurodatacube/eodash/files/11747387/Balaton_dates.txt)
[Biwa_dates.txt](https://github.com/eurodatacube/eodash/files/11747388/Biwa_dates.txt)
[Vanern_dates.txt](https://github.com/eurodatacube/eodash/files/11747389/Vanern_dates.txt)

**Comment by lubojr** [comment]
> @lubojr
> 
> > https://services.sentinel-hub.com/ogc/wfs/sh-id?REQUEST=GetFeature&srsName=EPSG:4326&TIME=1900-01-01/3000-02-01&outputformat=application/json&TYPENAMES=DSS10-ef59d045-a0cd-4ce0-a25d-5da91e70e965&BBOX=-180,90,180,-90
> 
> Please use TYPENAMES=`zarr-ef59d045-a0cd-4ce0-a25d-5da91e70e965`
> 
> It is a zarr collection, that is why

This returns ```<![CDATA[ TYPENAME=zarr-ef59d045-a0cd-4ce0-a25d-5da91e70e965 not found! ]]>```

**Comment by santilland** [comment]
@AlessandroScremin and @dmoglioni the Jupyter Notebook for lake detection without clouds is great, the idea would be to present it at the foss4g workshop, as you won't be able to attend EOX would present it in your name (with clear credit to Rhea and authors).
With @aapopescu it was discussed if it would be possible for you to extend the notebook to do some basic area measuring of the lake based on the filtered data and also if possible how the generated result could be added to geodb

**Comment by Dorothyrono** [comment]
@lubojr 

> https://services.sentinel-hub.com/ogc/wfs/sh-id?REQUEST=GetFeature&srsName=EPSG:4326&TIME=1900-01-01/3000-02-01&outputformat=application/json&TYPENAMES=zarr-ef59d045-a0cd-4ce0-a25d-5da91e70e965&BBOX=-180,90,180,-90  

Also the layers should be availble in the sh -instance id you are using. 

if you are using sh-id that ends with `..47c7` it should work now, otherwise let me know which instance id you are using

**Comment by lubojr** [comment]
@aapopescu

Empty markdown files for Lakes indicators that I am so far aware of are added at:

https://github.com/eurodatacube/eodash/tree/cci-lakes-integration/app/public/data/trilateral

If you do not need some of them (so that two indicators will share the same markdown), then feel free to delete the extra one and I will configure 2 indicators to share a md file.

file name|indicator
-- | --
LWE.md(File) | Lake Water Extent timeseries Varne
LWL.md(File) | Lake Water Level timeseries
Lakes_SWT.md(File) | Surface Water Temperature Lakes
Lakes_SWTT.md(File) | Surface Water Temperature Time Series
Lakes_S2L2A.md(File) | Sentinel 2 L2A for Lake areas
Lakes_WQ_TC.md(File) | Water Quality True color Lakes
Lakes_WQ_TURB.md(File) | Water Quality Turbidity mean Lakes

**Comment by Dorothyrono** [comment]
Hi @AlessandroScremin 

I have copied  the right visualisation for LWQ true color and turbidity where the non lake-pixes are transparent,  to your SH account   
see `[NEW] LWQ - test layers` 

This is the legend used for turbidity

![image](https://github.com/eurodatacube/eodash/assets/49271738/e8dcf59b-fef0-438b-a0e5-a62a36f9776c)

**Comment by AlessandroScremin** [comment]
@Dorothyrono 

thnaks a lot for the support, really appreciated

@lubojr 
layers in EDC for race have beeen updated accordigly with what @Dorothyrono provide.

Let me know

ALessandro

**Comment by AlessandroScremin** [comment]
> With @aapopescu it was discussed if it would be possible for you to extend the notebook to do some basic area measuring of the lake based on the filtered data and also if possible how the generated result could be added to geodb

hi @santilland  and @aapopescu 
I tried to organize at best this task, but unfortuantely I can not provide the complete workflow as I will be on holiday (already today, but am wotking on it anyway).

What I can provide by Today is an additional set of cells in which looking at the Sentinel 2 acquistion filtered bu full COverage AOI and CC<30%,, I can use the SCL layer and flag the pixels that belong to class 6 (water) and count the number of those pixels, and multiply it by the area of each pixel with pixel size of 100m (and convert in km). I can not go at higher resolution for the limitation of Sentinel hub that allow to use statistical api only for tiles of 2500x2500 pixels. To do that I would need to implement a loop that collect al the tiles, compute area for each of them and then merge the results. As said not feasible for the workshop, but I can provide it using pixel size of 100m, it can be done without other implementation, and the results are quite valid for demonstration purposes...

0      2021-03-05T00:00:00Z	5465.38
1	2021-04-04T00:00:00Z	5197.70
2	2021-04-14T00:00:00Z	5369.04
3	2021-04-19T00:00:00Z	5436.52
4	2021-04-24T00:00:00Z	4035.80
5	2021-05-19T00:00:00Z	5248.66
6	2021-05-29T00:00:00Z	5446.44
7	2021-06-03T00:00:00Z	5390.43
8	2021-06-13T00:00:00Z	5234.46
9	2021-06-28T00:00:00Z	5119.17
10	2021-07-03T00:00:00Z	5320.59
11	2021-07-23T00:00:00Z	4313.01

**Comment by AlessandroScremin** [comment]
@lubojr @santilland cc: @aapopescu 

here the notebook ready with the last changes I proposed above.

kr

Alessandro
[OpenJN_Retrieve_areas_estimations_over_lakes_foss4g_ready.zip](https://github.com/eurodatacube/eodash/files/11788567/OpenJN_Retrieve_areas_estimations_over_lakes_foss4g_ready.zip)

**Comment by lubojr** [comment]
I will double check.

**Comment by j08lue** [comment]
We finally have the Landsat 7-9 collections ready in VEDA STAC staging. Here are the collection names:

1. Aral Sea - https://staging-stac.delta-backend.com/collections/landsat-c2l2-sr-lakes-aral-sea
2. Lake Balaton - https://staging-stac.delta-backend.com/collections/landsat-c2l2-sr-lakes-lake-balaton
3. Lake Biwa - https://staging-stac.delta-backend.com/collections/landsat-c2l2-sr-lakes-lake-biwa
4. Tonlé Sap - https://staging-stac.delta-backend.com/collections/landsat-c2l2-sr-lakes-tonle-sap
5. Vänern - https://staging-stac.delta-backend.com/collections/landsat-c2l2-sr-lakes-vanern

Here is an example tiler URL for a natural color RGB composite:

https://staging-raster.delta-backend.com/stac/tiles/WebMercatorQuad/8/201/118@2x?collection=landsat-c2l2-sr-lakes-tonle-sap&item=LC09_L2SP_127051_20230221_02_T1&assets=red&assets=green&assets=blue&color_formula=gamma+RGB+2.7%2C+saturation+1.5%2C+sigmoidal+RGB+15+0.55&nodata=0&format=png

@santilland, please let me know if more is needed from me at this point to ease the integration.

**Comment by santilland** [comment]
Great @j08lue ! I think that should be all that we need, we will try to integrate as soon as possible

**Comment by santilland** [comment]
@j08lue Initial integration looks good, will add link to the test branch in a bit, there seems to strangely be some issue for some of the datasets, for example for the Tonle sap lake on the 2023-03-10 it looks like this when zooming in:
![image](https://github.com/eurodatacube/eodash/assets/4036819/aafe9051-2c5e-4c27-871d-5a4b17d5f47d)
but for another day/dataset (2022-12-20) it looks like this:
![image](https://github.com/eurodatacube/eodash/assets/4036819/2ce39dfe-e4a7-4c1f-af29-dec0e35a81b7)
So i think this must be comming from the renderer, maybe a reprojection issue? when zoomed out it is much less noticeable:
![image](https://github.com/eurodatacube/eodash/assets/4036819/71e73257-8548-4869-9b54-1904262cf4e9)

It also seems that in the center of the scene the stripes disappear

**Comment by j08lue** [comment]
These are issues in the actual data - scenes where you see this should all be Landsat-7 (https://gis.stackexchange.com/questions/420546/noisy-lines-in-all-scenes-for-landsat-7).

Should we remove these scenes (Landsat-7 past 2003) or are they still useful, despite the artifacts?

**Comment by aapopescu** [comment]
Thanks, @j08lue, let's check with NASA colleagues for this.

We agreed with NASA to add one more location: Lake Tulare - as presented here: https://earthobservatory.nasa.gov/images/151284/tulare-lake-grows . Would be great if you could add the data over this area too. 

Thanks a lot!

**Comment by aapopescu** [comment]
> > > @leahsturm to provide list of s2 acquisition dates (taken from https://apps.sentinel-hub.com/eo-browser/) looking for good visibility (as little cloud cover as possible) and where changes in lake extent can be seen --> EOX to add s2 indicator with dates for lakes with provided dates
> > 
> > 
> > Here is the list with the Sentinel2 acquisition dates. I noted down the most possible number of cloud free images for each lake to ensure an extensive documentation of the change processes. [Sentinel2_lakes.xlsx](https://github.com/eurodatacube/eodash/files/11707292/Sentinel2_lakes.xlsx)
> 
> Thanks, @leahsturm, this is great! @lubojr (Cc: @santilland ) we should integrate these S-2 images over the lakes in the list. Thanks!

Cc: @leahsturm, this is the new lake for which we need the S-2  dates: https://earthobservatory.nasa.gov/images/151284/tulare-lake-grows

**Comment by santilland** [comment]
@aapopescu i added lake Tulare to the all_lakes test branch. I currently used a list of s2 dates for another lake, which seems to work relatively well, but there are some cloudy scenes.
@AlessandroScremin could you provide a list of cloudless dates for s2? The location of the lake is:
latLng([36.0508, -119.7830])
I used following polygon, e.g. as WKT:
POLYGON((-119.986955 36.176881, -119.488389 36.176881, -119.488389 35.706412,-119.986955 35.706412 ,-119.986955 36.176881))

**Comment by AlessandroScremin** [comment]
@santilland @lubojr  cc: @aapopescu 
ALOS2 from Jaxa, SAR over Tonle Lake is ingested in EDC. Here the two Jaxa Layers

ID: JAXA_LAKES_ALOS2_HH - aa8a9899-9df9-4ea0-b983-34360d583e17

ID: JAXA_LAKES_ALOS2_HV - 7820f4b8-0270-438e-83da-18de27fc539c

ID: SENTINEL_1_IW_VH - Sentinel-1 GRD
ID: SENTINEL_1_IW_VV - Sentinel-1 GRD

they are SAR images, don't think you need the eval script.



These are the dates Jaxa analyzed for ALOS2 - 

[Formatted ALOS2 date.csv](https://github.com/eurodatacube/eodash/files/11905684/Formatted.ALOS2.date.csv)


These are the dates Jaxa analyzed for sentinel 1 - 

[Formatted S1 date.csv](https://github.com/eurodatacube/eodash/files/11905565/Formatted.S1.date.csv)

**Comment by santilland** [comment]
Hello @AlessandroScremin trying to integrate the JAXA_LAKES_ALOS2_HH I only get completely black scenes when loading the layer, could you recheck the configuration?
Also i think there is an issue with the dates provided as there is for example a date in the future: 2024-08-22

**Comment by santilland** [comment]
@AlessandroScremin  for SENTINEL_1_IW_VH and  SENTINEL_1_IW_VV i strangely only get completely transparent png responses from the sentinelhub wms, could you also please recheck, loading of the layer is done as for other SH layers, so I don't think the issue is on the client.

**Comment by santilland** [comment]
Also there are repeated dates in the list of S1 dates

**Comment by santilland** [comment]
> @santilland Really sorry...made a mistake in date extraction. I will investigate S1. You are right they have duplicated date...but times should be different.
> 
@AlessandroScremin ALOS2 data looks good now.
For Sentinel 1 i still get "empty" transparent tiles for these dates

**Comment by AlessandroScremin** [comment]
@santilland 
I checked again and can't replicate that issue for Sentinel 1. I lase checked the dates, and we need both images in the same day to cover the entire Lake, so discard the time and consider only the date from the list above

anyway I changed a bit parameters...let me know

![image](https://github.com/eurodatacube/eodash/assets/65602207/410b0c2e-3fa8-4142-8428-5267fd62d11f)

**Comment by santilland** [comment]
> @santilland I checked again and can't replicate that issue for Sentinel 1. I lase checked the dates, and we need both images in the same day to cover the entire Lake, so discard the time and consider only the date from the list above
> 
I don't understand why it does not render anything, the layers in your screenshot are called S1_VH and S1_VV were are accessing SENTINEL_1_IW_VH and SENTINEL_1_IW_VV are you sure you are looking at the same thing?
Here is an example WMS request of the area, i extended the timeframe to be 2 months:

https://services.sentinel-hub.com/ogc/wms/0635c213-17a1-48ee-aef7-9d1731695a54?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image/png&TRANSPARENT=true&layers=SENTINEL_1_IW_VV&format=image/png&time=2018-10-20/2018-12-21&WIDTH=512&HEIGHT=512&CRS=EPSG:3857&STYLES=&BBOX=11740727.544603072,1252344.271424327,11897270.578531113,1408887.305352368

**Comment by AlessandroScremin** [comment]
@santilland 

Ok now it works...really strnage...I needed to change the resolution from medium to high...nothing else...

I didn't thought it was ONLY for that...

let me know
Alessandro

**Comment by santilland** [comment]
Very strange indeed, thank you for finding the issue. The Jaxa lake data is now available in following branch deployment:
https://eodash-trilateral-testing.eox.at/jaxa_lakes/
only description would be missing @aapopescu the placeholder markdown files are following:
https://github.com/eurodatacube/eodash/blob/jaxa_lakes/app/public/data/trilateral/Lakes_Sentinel1.md
https://github.com/eurodatacube/eodash/blob/jaxa_lakes/app/public/data/trilateral/Lakes_ALOS2.md

**Comment by AlessandroScremin** [comment]
@aapopescu @santilland 

I take the action to find and process ARAL Lakes Surface water temperatures.

If needed I can already provide the ARAL LSWT maps (they are in the same collections already, so you only need to harvest the new AOI) see image for output results

I also generated the timeseries for ARAL Lake. In this case I would require you green light before ingesting them in the GeoDB.

let me know.

Alessandro

![image](https://github.com/eurodatacube/eodash/assets/65602207/704d6dcf-3856-46b8-a90e-492eeb9496cf)

**Comment by AlessandroScremin** [comment]
> > > > @leahsturm to provide list of s2 acquisition dates (taken from https://apps.sentinel-hub.com/eo-browser/) looking for good visibility (as little cloud cover as possible) and where changes in lake extent can be seen --> EOX to add s2 indicator with dates for lakes with provided dates
> > > 
> > > 
> > > Here is the list with the Sentinel2 acquisition dates. I noted down the most possible number of cloud free images for each lake to ensure an extensive documentation of the change processes. [Sentinel2_lakes.xlsx](https://github.com/eurodatacube/eodash/files/11707292/Sentinel2_lakes.xlsx)
> > 
> > 
> > Thanks, @leahsturm, this is great! @lubojr (Cc: @santilland ) we should integrate these S-2 images over the lakes in the list. Thanks!
> 
> Cc: @leahsturm, this is the new lake for which we need the S-2 dates: https://earthobservatory.nasa.gov/images/151284/tulare-lake-grows

I don't know if Leah already provided the cloud free dates...I used the notebook presented to the FOSS4G

Acquisition: 2023-01-01T00:00:00Z - pixels with no data 0 - cloud coverage over AOI is 5 %
Acquisition: 2023-01-06T00:00:00Z - pixels with no data 0 - cloud coverage over AOI is 20 %
Acquisition: 2023-01-21T00:00:00Z - pixels with no data 0 - cloud coverage over AOI is 0 %
Acquisition: 2023-01-26T00:00:00Z - pixels with no data 0 - cloud coverage over AOI is 0 %
Acquisition: 2023-01-31T00:00:00Z - pixels with no data 0 - cloud coverage over AOI is 2 %
Acquisition: 2023-02-05T00:00:00Z - pixels with no data 0 - cloud coverage over AOI is 19 %
Acquisition: 2023-02-10T00:00:00Z - pixels with no data 0 - cloud coverage over AOI is 29 %
Acquisition: 2023-02-15T00:00:00Z - pixels with no data 0 - cloud coverage over AOI is 0 %
Acquisition: 2023-03-02T00:00:00Z - pixels with no data 0 - cloud coverage over AOI is 0 %
Acquisition: 2023-03-07T00:00:00Z - pixels with no data 0 - cloud coverage over AOI is 1 %
Acquisition: 2023-03-27T00:00:00Z - pixels with no data 0 - cloud coverage over AOI is 0 %
Acquisition: 2023-04-01T00:00:00Z - pixels with no data 0 - cloud coverage over AOI is 0 %
Acquisition: 2023-04-06T00:00:00Z - pixels with no data 0 - cloud coverage over AOI is 0 %
Acquisition: 2023-04-11T00:00:00Z - pixels with no data 0 - cloud coverage over AOI is 0 %
Acquisition: 2023-04-21T00:00:00Z - pixels with no data 0 - cloud coverage over AOI is 0 %
Acquisition: 2023-04-26T00:00:00Z - pixels with no data 0 - cloud coverage over AOI is 0 %
Acquisition: 2023-05-11T00:00:00Z - pixels with no data 0 - cloud coverage over AOI is 0 %
Acquisition: 2023-05-16T00:00:00Z - pixels with no data 0 - cloud coverage over AOI is 12 %
Acquisition: 2023-05-21T00:00:00Z - pixels with no data 0 - cloud coverage over AOI is 0 %
Acquisition: 2023-05-26T00:00:00Z - pixels with no data 0 - cloud coverage over AOI is 1 %

**Comment by leahsturm** [comment]
> 



> > > > @leahsturm to provide list of s2 acquisition dates (taken from https://apps.sentinel-hub.com/eo-browser/) looking for good visibility (as little cloud cover as possible) and where changes in lake extent can be seen --> EOX to add s2 indicator with dates for lakes with provided dates
> > > 
> > > 
> > > Here is the list with the Sentinel2 acquisition dates. I noted down the most possible number of cloud free images for each lake to ensure an extensive documentation of the change processes. [Sentinel2_lakes.xlsx](https://github.com/eurodatacube/eodash/files/11707292/Sentinel2_lakes.xlsx)
> > 
> > 
> > Thanks, @leahsturm, this is great! @lubojr (Cc: @santilland ) we should integrate these S-2 images over the lakes in the list. Thanks!
> 
> Cc: @leahsturm, this is the new lake for which we need the S-2 dates: https://earthobservatory.nasa.gov/images/151284/tulare-lake-grows

Here is the new list of cloud free images for lake Tulare. I noted down the dates only for the years 2023 and 2022 because the lake is not visible on the satellite images before major storm events in March 2023. 


[tulare_lake.xlsx](https://github.com/eurodatacube/eodash/files/11945929/tulare_lake.xlsx)

**Comment by AlessandroScremin** [comment]
@santilland @lubojr 

New AOI for ARAL

- new aoi Lake Water surface Temperature maps
- new aoi Aral Lake Water surface Temperature timeseries added to geodb

**Comment by AlessandroScremin** [comment]
Dears @santilland @lubojr 
I Still don't see any Timeseries for the Lake water surface temperature in 
https://eodash-trilateral-staging.eox.at/

Still under implementation right?


another question could you pelase add 
Federico to eodash github space please?
github mail of federico
federico.rondoni@community.isunet.edu

**Comment by santilland** [comment]
> Dears @santilland @lubojr I Still don't see any Timeseries for the Lake water surface temperature in https://eodash-trilateral-staging.eox.at/

Do you mean the use of the statiscal api for the lake water surface temperature datasets? I will have a look at how the results look and let you know.

If i am not mistaken Federico should now been added, correct?
