### ISSUE TITLE
Different AOIs is same AOI (in Los Angeles) only one is displayed 

### ISSUE THREAD

**Issue by AlessandroScremin** [eurodatacube/eodash#2311]
Replicate the issue: 
In Los Angeles there are dirrent activity indicator AOIs. But when I search for them with the search bar I can found only one general Los Angeles: activity indicator that point only to one AOIs, but no information which AOI it is.
also in the chart no information about which one it is. 
![image](https://github.com/eurodatacube/eodash/assets/65602207/4214b84e-09d5-421e-8221-e386cd7967fd)

here some of the AOIs called generically Los Angeles.
![image](https://github.com/eurodatacube/eodash/assets/65602207/919ef02d-e2fd-4de8-ae71-6ec1be59c868)

in the geodb there are additional information about the AOIID and the Site name that can be used to have more detailed info on the same Region or City.

The last problem is the AOI for Los Angeles Activty indicator for the LAX airport. Clicking on it the AOI is moing in Japan instead of Los Angeles

from here https://eodashboard.org/explore?x=-13181279.84858&y=4020714.45793&z=14.06978&clusterOpen=2

![image](https://github.com/eurodatacube/eodash/assets/65602207/72ac9c75-a338-4096-85a7-e84df5d5ecfe)

im moved to:
https://eodashboard.org/explore?x=15566322.04375&y=4237455.71806&z=12.59719&clusterOpen=2&poi=US021-E9&search=Los+Angeles%3A+Activity+indicator
in japas as for image

![image](https://github.com/eurodatacube/eodash/assets/65602207/d802fe23-5747-47f7-9fcd-0ad4ed2575cf)

**Comment by lubojr** [comment]
Also linking related comment https://github.com/eurodatacube/eodash/pull/2294#issuecomment-1689657502 regarding investigation on the activity datasets and jaxa data.

I have had a look at the US021-E9 AOI in our cached JSONs and the SUBAOI needs to be updated correctly in GEODB. Currently it has value POLYGON((139.74970 35.57515, 139.74970 35.51883, 139.82882 35.51883, 139.82882 35.57515, 139.74970 35.57515)).

Also I have noticed that some data for this combination of AOI and POI are duplicated in the database - see https://github.com/eurodatacube/eodash/blob/staging/app/public/data/internal/US021-E9.json#L1223-L1244

The first problem reported (inability to choose concrete POI) should get solved by the new filtering panel, which is being worked on.

**Comment by AlessandroScremin** [comment]
@dmoglioni
could you please verify the duplicates Lubo reported?

**Comment by AlessandroScremin** [comment]
@dmoglioni @aapopescu 

About the issue of the AOI...I still don't receive the new contact about the Activity indicator from Jaxa...

But looking at the maps, the issue is related to the Los ANgele s international Airport...this means that from my side the AOI can be changed with the following if you agree:

 POLYGON ((241.547974 33.964007, 241.633106 33.964007, 241.633621 33.926127, 241.548488 33.925984, 241.547974 33.964007)))
 
 
![image](https://github.com/eurodatacube/eodash/assets/65602207/2134c626-233b-4453-b9e6-95fc98355b6d)

**Comment by AlessandroScremin** [comment]
Please @dmoglioni  could you update us here when the change of Polygon and the removal of duplicates is completed?
Thnaks a lot

Ale

**Comment by dmoglioni** [comment]
Sure @AlessandroScremin

**Comment by dmoglioni** [comment]
@AlessandroScremin 

E9_tri duplicates removed and US021 sub-aoi modified as:

POLYGON((241.547974 33.964007,241.633106 33.964007,241.633621 33.926127,241.548488 33.925984,241.547974 33.964007))

**Comment by AlessandroScremin** [comment]
@lubojr   cc: @aapopescu @dmoglioni 

hi Lubo, could you please update with the neew AOI and double chck dubplicates?

kr
Ale

**Comment by lubojr** [comment]
Confirmed that it is fixed. Thank you!
